### ISSUE TITLE
PyPy interpreter not being selected

### ISSUE THREAD

**Issue by moomoohk** [ymyzk/run-tox-gh-actions#3]
I can't seem to get this action to run tests with pypy.

Running tox with `-vv` produces this output (empty envlist):
```
original envconfigs: ['py36', 'pypy37', 'py38', 'py39', 'flake8']
original envlist_default: ['py36', 'pypy37', 'py38', 'py39', 'flake8']
original envlist: ['py36', 'pypy37', 'py38', 'py39', 'flake8']
Python versions: ['pypy-3.7', 'pypy-3', 'pypy3']
tox-gh-actions config: {'python': {'3.6': ['py36'], 'pypi-3.7': ['pypy37'], '3.8': ['py38'], '3.9': ['py39', 'flake8']}, 'env': {}}
using the following factors to decide envlist: []
overriding envlist with: []
```

Compare with output for CPython 3.9 (valid envlist):
```
original envconfigs: ['py36', 'pypy37', 'py38', 'py39', 'flake8']
original envlist_default: ['py36', 'pypy37', 'py38', 'py39', 'flake8']
original envlist: ['py36', 'pypy37', 'py38', 'py39', 'flake8']
Python versions: ['3.9', '3']
tox-gh-actions config: {'python': {'3.6': ['py36'], 'pypi-3.7': ['pypy37'], '3.8': ['py38'], '3.9': ['py39', 'flake8']}, 'env': {}}
got factors for Python version: 3.9
using the following factors to decide envlist: ['py39', 'flake8']
overriding envlist with: ['py39', 'flake8']
```

Here is my code:

`tox.ini`:
```ini
[tox]
envlist = py36, pypy37, py38, py39, flake8

[gh-actions]
python =
    3.6: py36
    pypi-3.7: pypy37
    3.8: py38
    3.9: py39, flake8
```

`action.yml`:
```yml
    strategy:
      matrix:
        # Match versions specified in tox.ini
        python-version: [3.6, 3.8, 3.9, pypy-3.7]
  
    # Steps represent a sequence of tasks that will be executed as part of the job    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    
    # Instead of installing and running tox and tox-gh-actions,
    # you can simply use this composite run steps action.
    - name: Run tox with tox-gh-actions
      uses: ymyzk/run-tox-gh-actions@main
      with:
        tox-args: -vv
```

Any help would be appreciated.
